version: "2"
# Configure containers for RSuite 3.6 
#
#
# Set the following environment variables (e.g., in .env in the
# directory you run docker-compose in):
#
# RSUITE_MODULES: Directory containing the RSuite XQuery modules
# RSUITE_PLUGINS: Directory containing the RSuite plugins.
# RSUITE_HOTFOLDERS: Directory for RSuite hot folders
#
#=======================================================

volumes:
  rsuiteData:
  mlData:
  mlWork:
  mysqlData:
  backup:
  
services:

  marklogic:
#     image: jkapadnis/centos6-marklogic7
     image: rsd/ml:4.2
     container_name: marklogic
     ports:
       # CQ:
       - 9100:8000
       # Admin:
       - 9101:8001
       - 9102:8002
       # RSuite xdbc app:
       - 9136:9036
       
     volumes:
       - mlData:/opt/data/forests:Z
       - mlWork:/var/opt/MarkLogic:Z
       - ${RSUITE_MODULES}:/opt/data/modules
       - backup:/var/opt/mlbackup
  
  mysql:
     image: mtirsel/mysql-5.1
     container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=admin
       - MYSQL_HOST=mysql
     ports:
       - 9306:3306

     volumes:
       - mysqlData:/var/lib/mysql:Z
  
  rsuite:
     image: rsd/rsuite:3.6
     container_name: rsuite
     ports:
       - 9180:8080
       
     volumes:
       - rsuiteData:/opt/rsuite/rsuite-data:Z
       - ${RSUITE_PLUGINS}:/opt/RSuite/plugins:Z
       - ${RSUITE_MODULES}:/opt/RSuite/modules_1_0:Z
       - ${RSUITE_HOTFOLDERS}:/marklogic/RSuite-data/hotfolders:Z
     
     depends_on:
      - marklogic
      - mysql
     
  
   