version: "2"
# Configure containers for RSuite 3.6 
#
#
# Set the following environment variables (e.g., in .env in the
# directory you run docker-compose in):
#
# RSUITE_MODULES: Directory containing the RSuite XQuery modules
# RSUITE_PLUGINS: Directory containing the RSuite plugins.
# RSUITE_HOTFOLDERS: Directory for RSuite hot folders
#
#=======================================================

volumes:
  mlData:
  mlWork:
  mysqlData:
  backup:
  
services:

  marklogic:
#     image: jkapadnis/centos6-marklogic7
     image: m1/ml:4.2
     container_name: marklogic
     ports:
       # CQ:
       - 9100:8000
       # Admin:
       - 9101:8001
       - 9102:8002
       # RSuite xdbc app:
       - 9136:9036
       
     volumes:
       - mlData:/opt/data/forests:Z
       - mlWork:/var/opt/MarkLogic:Z
       - ${RSUITE_MODULES}:/opt/data/modules
       - backup:/var/opt/mlbackup
  
#
# End of docker-compose file
#
   